export const MOCK_RESTAURANTS = [
  {
    id: "1",
    name: "Little Caesars Humaya",
    cuisine: "Pizza",
    rating: 4.5,
    fromPrice: 189,
    platforms: 2,
    imageUrl: "",
  },
  {
    id: "2",
    name: "McDonald's Forum",
    cuisine: "Hamburguesas",
    rating: 4.2,
    fromPrice: 99,
    platforms: 3,
    imageUrl: "",
  },
  {
    id: "3",
    name: "El Pollo Loco",
    cuisine: "Pollo",
    rating: 4.7,
    fromPrice: 129,
    platforms: 2,
    imageUrl: "",
  },
  {
    id: "4",
    name: "Sushi Itto",
    cuisine: "Sushi",
    rating: 4.3,
    fromPrice: 219,
    platforms: 2,
    imageUrl: "",
  },
  {
    id: "5",
    name: "Tacos El Guero",
    cuisine: "Tacos",
    rating: 4.8,
    fromPrice: 75,
    platforms: 1,
    imageUrl: "",
  },
  {
    id: "6",
    name: "Domino's Pizza",
    cuisine: "Pizza",
    rating: 4.1,
    fromPrice: 159,
    platforms: 3,
    imageUrl: "",
  },
];

export const MOCK_COMPARE = {
  restaurant: "Little Caesars Humaya",
  product: {
    name: "Combo Crazy Puffs",
    description: "Pizza mediana + Crazy Puffs + refresco 600ml",
    imageUrl: "",
  },
  quotes: [
    {
      platform: "rappi" as const,
      productPrice: 189,
      deliveryFee: 35,
      serviceFee: 0,
      total: 224,
      etaMinutes: 30,
      deepLink: "https://www.rappi.com.mx",
    },
    {
      platform: "ubereats" as const,
      productPrice: 189,
      deliveryFee: 25,
      serviceFee: 17,
      total: 231,
      etaMinutes: 25,
      deepLink: "https://www.ubereats.com",
    },
    {
      platform: "didi" as const,
      productPrice: 189,
      deliveryFee: 29,
      serviceFee: 0,
      total: 218,
      etaMinutes: 35,
      deepLink: "https://food.didiglobal.com",
    },
  ],
};
